# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: component.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63omponent.proto\"\x15\n\x05Image\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x1d\n\x05Poses\x12\x14\n\x05poses\x18\x01 \x03(\x0b\x32\x05.Pose\"%\n\x04Pose\x12\x1d\n\nkey_points\x18\x01 \x03(\x0b\x32\t.KeyPoint\"+\n\x08KeyPoint\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x32N\n\x11OpenPoseEstimator\x12\x1a\n\x08\x65stimate\x12\x06.Image\x1a\x06.Poses\x12\x1d\n\x0b\x65stimateImg\x12\x06.Image\x1a\x06.Imageb\x06proto3')



_IMAGE = DESCRIPTOR.message_types_by_name['Image']
_POSES = DESCRIPTOR.message_types_by_name['Poses']
_POSE = DESCRIPTOR.message_types_by_name['Pose']
_KEYPOINT = DESCRIPTOR.message_types_by_name['KeyPoint']
Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), {
  'DESCRIPTOR' : _IMAGE,
  '__module__' : 'component_pb2'
  # @@protoc_insertion_point(class_scope:Image)
  })
_sym_db.RegisterMessage(Image)

Poses = _reflection.GeneratedProtocolMessageType('Poses', (_message.Message,), {
  'DESCRIPTOR' : _POSES,
  '__module__' : 'component_pb2'
  # @@protoc_insertion_point(class_scope:Poses)
  })
_sym_db.RegisterMessage(Poses)

Pose = _reflection.GeneratedProtocolMessageType('Pose', (_message.Message,), {
  'DESCRIPTOR' : _POSE,
  '__module__' : 'component_pb2'
  # @@protoc_insertion_point(class_scope:Pose)
  })
_sym_db.RegisterMessage(Pose)

KeyPoint = _reflection.GeneratedProtocolMessageType('KeyPoint', (_message.Message,), {
  'DESCRIPTOR' : _KEYPOINT,
  '__module__' : 'component_pb2'
  # @@protoc_insertion_point(class_scope:KeyPoint)
  })
_sym_db.RegisterMessage(KeyPoint)

_OPENPOSEESTIMATOR = DESCRIPTOR.services_by_name['OpenPoseEstimator']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMAGE._serialized_start=19
  _IMAGE._serialized_end=40
  _POSES._serialized_start=42
  _POSES._serialized_end=71
  _POSE._serialized_start=73
  _POSE._serialized_end=110
  _KEYPOINT._serialized_start=112
  _KEYPOINT._serialized_end=155
  _OPENPOSEESTIMATOR._serialized_start=157
  _OPENPOSEESTIMATOR._serialized_end=235
# @@protoc_insertion_point(module_scope)
