# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import visualization_proto_pb2 as visualization__proto__pb2


class ImageVisualizationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Visualize = channel.unary_unary(
                '/ImageVisualizationService/Visualize',
                request_serializer=visualization__proto__pb2.Image.SerializeToString,
                response_deserializer=visualization__proto__pb2.Empty.FromString,
                )


class ImageVisualizationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Visualize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageVisualizationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Visualize': grpc.unary_unary_rpc_method_handler(
                    servicer.Visualize,
                    request_deserializer=visualization__proto__pb2.Image.FromString,
                    response_serializer=visualization__proto__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ImageVisualizationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ImageVisualizationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Visualize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ImageVisualizationService/Visualize',
            visualization__proto__pb2.Image.SerializeToString,
            visualization__proto__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
