# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: visualization_proto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19visualization_proto.proto\"\x15\n\x05Image\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x07\n\x05\x45mpty28\n\x19ImageVisualizationService\x12\x1b\n\tVisualize\x12\x06.Image\x1a\x06.Emptyb\x06proto3')



_IMAGE = DESCRIPTOR.message_types_by_name['Image']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), {
  'DESCRIPTOR' : _IMAGE,
  '__module__' : 'visualization_proto_pb2'
  # @@protoc_insertion_point(class_scope:Image)
  })
_sym_db.RegisterMessage(Image)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'visualization_proto_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

_IMAGEVISUALIZATIONSERVICE = DESCRIPTOR.services_by_name['ImageVisualizationService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMAGE._serialized_start=29
  _IMAGE._serialized_end=50
  _EMPTY._serialized_start=52
  _EMPTY._serialized_end=59
  _IMAGEVISUALIZATIONSERVICE._serialized_start=61
  _IMAGEVISUALIZATIONSERVICE._serialized_end=117
# @@protoc_insertion_point(module_scope)
